seq = input()
print("Sequence:", seq)
lgt = len(seq)
a = seq.count("A")
t = seq.count("T")
c = seq.count("C")
g = seq.count("G")
prc = ((c + g) / lgt) * 100
print("Length:", lgt)
print("A:", a)
print("T:", t)
print("C:", c)
print("G:", g)
print("GC:", prc)
